### PR TITLE
Conv1D layer: check for legacy shape of weights

### PR DESCRIPTION
**Pull request by stekaiser**
Keras changed the ordering of the weights (see https://github.com/fchollet/keras/commit/9f6acd960c0a0c699c79ca1d571783e1692568fb and https://github.com/fchollet/keras/commit/305b3bed747bb8dd358cf82d11bcb1aee5b6e517).

This will only transpose the weights if in legacy format. Fixes issue #22.

### CODE REVIEW

**Comment by transcranial** [comment]
Thanks! Merged in https://github.com/transcranial/keras-js/commit/748d49bb77f9d8f547f5b7c09822d7a975b7008a.

**Comment by stekaiser** [comment]
Thanks for merging and mentioning me in the commit message. One question though, would it be possible to merge the changes in a way that GitHub is able to pick it up as a contribution?

**Comment by transcranial** [comment]
@stekaiser np, can you sync up with master?

**Comment by stekaiser** [comment]
Thanks, I really appreciate it. Unfortunately, just syncing up with master doesn't do it.

If I try rebasing my changes git tells me that the patch is already applied. I guess we would have to undo the commit?

**Comment by stekaiser** [comment]
@transcranial :bowing_man: thanks a lot!

**Comment by transcranial** [comment]
haha a lot of other stuff got rolled in there. oh well, doesn't matter. thanks again.

**Pull request merged**
